export enum CallStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ENDED = 'ENDED',
}

export enum OrderStatus {
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export enum ConversationState {
  IDLE = 'IDLE',
  LISTENING = 'LISTENING',
  TRANSCRIBING = 'TRANSCRIBING',
  THINKING = 'THINKING',
  TOOL_EXECUTION = 'TOOL_EXECUTION',
  SPEAKING = 'SPEAKING',
  INTERRUPTED = 'INTERRUPTED',
  ENDING = 'ENDING',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
}

export enum MessageRole {
  CUSTOMER = 'CUSTOMER',
  AGENT = 'AGENT',
  SYSTEM = 'SYSTEM',
  TOOL = 'TOOL',
}

export enum CustomerIntent {
  ORDER_TRACKING = 'ORDER_TRACKING',
  ORDER_CANCELLATION = 'ORDER_CANCELLATION',
  RETURN_REQUEST = 'RETURN_REQUEST',
  POLICY_INQUIRY = 'POLICY_INQUIRY',
  PRODUCT_INQUIRY = 'PRODUCT_INQUIRY',
  GENERAL_INQUIRY = 'GENERAL_INQUIRY',
  OUT_OF_SCOPE = 'OUT_OF_SCOPE',
  UNKNOWN = 'UNKNOWN',
}

export enum ResolutionStatus {
  RESOLVED = 'RESOLVED',
  UNRESOLVED = 'UNRESOLVED',
  PARTIALLY_RESOLVED = 'PARTIALLY_RESOLVED',
  ESCALATED = 'ESCALATED',
}

export enum Language {
  ENGLISH = 'en',
  HINDI = 'hi',
  HINGLISH = 'hinglish',
  UNKNOWN = 'unknown',
}

export enum CircuitBreakerState {
  CLOSED = 'CLOSED',
  OPEN = 'OPEN',
  HALF_OPEN = 'HALF_OPEN',
}

export enum ErrorCode {
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  INVALID_ORDER_ID = 'INVALID_ORDER_ID',
  STT_FAILURE = 'STT_FAILURE',
  TTS_FAILURE = 'TTS_FAILURE',
  LLM_FAILURE = 'LLM_FAILURE',
  AI_ALL_PROVIDERS_FAILED = 'AI_ALL_PROVIDERS_FAILED',
  AUDIO_INVALID = 'AUDIO_INVALID',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  POLICY_DENIED = 'POLICY_DENIED',
  GUARDRAIL_VIOLATION = 'GUARDRAIL_VIOLATION',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  DATABASE_ERROR = 'DATABASE_ERROR',
  REDIS_ERROR = 'REDIS_ERROR',
  TIMEOUT = 'TIMEOUT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  OUT_OF_SCOPE = 'OUT_OF_SCOPE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  CIRCUIT_BREAKER_OPEN = 'CIRCUIT_BREAKER_OPEN',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
}
