import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(5000),
  MONGODB_URI: Joi.string().uri().required(),
  REDIS_URL: Joi.string().uri().required(),
  SARVAM_API_KEY: Joi.string().allow('').default(''),
  SARVAM_STT_MODEL: Joi.string().default('saarika:v2'),
  SARVAM_TTS_MODEL: Joi.string().default('bulbul:v2'),
  SARVAM_BASE_URL: Joi.string().uri().default('https://api.sarvam.ai'),
  LLM_PROVIDER: Joi.string().default('openai'),
  LLM_API_KEY: Joi.string().allow('').default(''),
  LLM_MODEL: Joi.string().default('gpt-4o-mini'),
  LLM_BASE_URL: Joi.string().uri().default('https://api.openai.com/v1'),
  LLM_FALLBACK_PROVIDER: Joi.string().allow('').default(''),
  LLM_FALLBACK_API_KEY: Joi.string().allow('').default(''),
  LLM_FALLBACK_MODEL: Joi.string().allow('').default(''),
  LLM_FALLBACK_BASE_URL: Joi.string().uri().allow('').default(''),
  JWT_SECRET: Joi.string().required(),
  CORS_ORIGIN: Joi.string().default('*'),
  LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'info', 'debug', 'trace').default('info'),
  AI_TIMEOUT_MS: Joi.number().default(15000),
  AI_MAX_RETRIES: Joi.number().default(2),
  RATE_LIMIT_TTL: Joi.number().default(60),
  RATE_LIMIT_LIMIT: Joi.number().default(60),
  CIRCUIT_BREAKER_THRESHOLD: Joi.number().default(5),
  CIRCUIT_BREAKER_COOLDOWN_MS: Joi.number().default(30000),
  SUMMARY_QUEUE_CONCURRENCY: Joi.number().default(2),
  CLEANUP_QUEUE_CONCURRENCY: Joi.number().default(1),
  SESSION_TTL_SECONDS: Joi.number().default(1800),
});
